#服务端口
server:
  port: 8083

spring:
  application:
    # 服务名
    name: edu-vod
  profiles:
    # 环境设置：dev、test、prod
    active: dev
  servlet:
    multipart:
      # 最大上传单个文件大小：默认1M
      max-file-size: 1024MB
      # 最大置总上传的数据大小 ：默认10M
      max-request-size: 1024MB

#阿里云 vod
#不同的服务器，地址不同
aliyun:
  vod:
    file:
      keyid: xxxxxxxxxxx
      keysecret: xxxxxxxxxxxxxx

eureka:
  client:
    service-url:
      #指定注册中心地址
      defaultZone: http://127.0.0.1:8084/eureka/
  instance:
    #eureka服务器上获取的是服务器的ip地址，否则是主机名
    prefer-ip-address: true
