#服务端口
server:
  port: 8084


eureka:
  client:
    #是否将自己注册到Eureka服务器中，本身是服务器，无需注册
    register-with-eureka: false
    #是否从Eureka中获取注册信息
    fetch-registry: false
    #Eureka客户端与Eureka服务端进行通信的地址
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka/
