# 服务端口
server:
  port: 8087
  # 服务名
spring:
  application:
    name: edu-email
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/edu?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 邮件配置
  mail:
    host: smtp.qq.com
    protocol: smtp
    default-encoding: UTF-8
    password: lfpspdqlwnetbadb
    username: 1443937284@qq.com
    port: 587
  redis:
    timeout: 10000ms
    host: 127.0.0.1
    port: 6379
    database: 0 # 选择哪个库，默认0库
    lettuce:
      pool:
        max-active: 1024 # 最大连接数，默认 8
        max-wait: 10000ms # 最大连接阻塞等待时间，单位毫秒，默认 -1
        max-idle: 200 # 最大空闲连接，默认 8
        min-idle: 5

eureka:
  client:
    service-url:
      #指定注册中心地址
      defaultZone: http://127.0.0.1:8084/eureka/
  instance:
    #eureka服务器上获取的是服务器的ip地址，否则是主机名
    prefer-ip-address: true

