server:
  port: 8086

spring:
  application:
    # 服务名
    name: edu-statistics
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/edu?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置mybatis数据返回类型别名
  type-aliases-package: com.example.statistics.pojo
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: false
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#打印mysql语句   (接口所在位置  不是mappering.xml文件位置)
logging:
  level:
    com.example.statistics.mapper: debug
#  file:
#    name: log/blog-dev.log

eureka:
  client:
    service-url:
      #指定注册中心地址
      defaultZone: http://127.0.0.1:8084/eureka/
  instance:
    #eureka服务器上获取的是服务器的ip地址，否则是主机名
    prefer-ip-address: true

