server:
  port: 8085

spring:
  application:
    # 服务名
    name: edu-user
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/edu?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    timeout: 10000ms
    host: 127.0.0.1
    port: 6379
    database: 0 # 选择哪个库，默认0库
    lettuce:
      pool:
        max-active: 1024 # 最大连接数，默认 8
        max-wait: 10000ms # 最大连接阻塞等待时间，单位毫秒，默认 -1
        max-idle: 200 # 最大空闲连接，默认 8
        min-idle: 5

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置mybatis数据返回类型别名
  type-aliases-package: com.example.user.pojo
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: false
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  global-config:
    db-config:
      logic-delete-field: is_deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

#打印mysql语句   (接口所在位置  不是mappering.xml文件位置)
logging:
  level:
    com.example.user.mapper: debug
#  file:
#    name: log/blog-dev.log

eureka:
  client:
    service-url:
      #指定注册中心地址
      defaultZone: http://127.0.0.1:8084/eureka/
  instance:
    #eureka服务器上获取的是服务器的ip地址，否则是主机名
    prefer-ip-address: true

